export type Usercreateform  ={
    employeeId:string,
    name: string,
    salary:number,
    grade:string,
    userName:string,
    email:string,
    basic:number,
    home:number,
    medical:number,
    conveyance:number,
    food:number,
    special:number,
    joinDate:Date
    section:string,
    category:string,
    designation:string,
    department:string,
    vill:string,
    thana:string,
    post:string,
    postCode:number,
    district:string,
    father : string,
    mother:string,
    blood:string,
    nid:string,
    dob: Date,
    phone:string
    certificate:string,
    qualification:string,
    nomineeName:string,
    relation:string
    account:string,
    bankName :string,
    route:number
}

export type Salarycreateform = {
    present:number,
    weekend:number,
    holidays:number,
    absent:number,
    casual:number,
    sick:number,
    earn:number,
    maternity:number,
    ot_hours:number,
    ot_rate:number,
    ot_amount:number,
    advanced:number,
    abseentism:number,
    loan:number,
    pf:number,
    others:number,
    tax:number
}